FORMAT: 1A
HOST: http://104.215.147.200:8069/xmllpc/common
# MF Odoo based - Api

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "uid": 1,
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "db": "MUF_14112018",
            "user": "admin",
            "password": "1",
        }
